version: '3.1'

services:

  db:
    image: postgres
    container_name: spring_playground_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: betterdex
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: spring_playground_adminer
    restart: unless-stopped
    ports:
      - "8085:8080"